-- VHDL Entity DASLIB.hdb3enc.interface
--
-- Created:
--          by - 879291.UNKNOWN (PC143412)
--          at - 12:40:28 22-03-2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.2a (Build 7)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY hdb3enc IS
   PORT( 
      clk       : IN     std_logic;
      nrst      : IN     std_logic;
      so        : IN     std_logic;
      syncadd_c : IN     std_logic;
      LWout     : OUT    std_logic;
      hmin      : OUT    std_logic;
      hnul      : OUT    std_logic;
      hplus     : OUT    std_logic
   );

-- Declarations

END hdb3enc ;

--
-- VHDL Architecture DASLIB.hdb3enc.struct1
--
-- Created:
--          by - 879291.UNKNOWN (PC143412)
--          at - 12:40:28 22-03-2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.2a (Build 7)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct1 OF hdb3enc IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL bits : std_logic_vector(3 DOWNTO 0);


   -- Component Declarations
   COMPONENT hdb3_1
   PORT (
      bits      : IN     std_logic_vector (3 DOWNTO 0);
      clk       : IN     std_logic ;
      nrst      : IN     std_logic ;
      syncadd_c : IN     std_logic ;
      LWout     : OUT    std_logic ;
      hmin      : OUT    std_logic ;
      hnul      : OUT    std_logic ;
      hplus     : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT hdb3reg_1
   PORT (
      clk  : IN     std_logic ;
      nrst : IN     std_logic ;
      so   : IN     std_logic ;
      bits : OUT    std_logic_vector (3 DOWNTO 0)
   );
   END COMPONENT;




BEGIN

   -- Instance port mappings.
   HDB3encS : hdb3_1
      PORT MAP (
         bits      => bits,
         clk       => clk,
         nrst      => nrst,
         syncadd_c => syncadd_c,
         LWout     => LWout,
         hmin      => hmin,
         hnul      => hnul,
         hplus     => hplus
      );
   HDB3regS : hdb3reg_1
      PORT MAP (
         clk  => clk,
         nrst => nrst,
         so   => so,
         bits => bits
      );

END struct1;
