##########################################
# digital design 21, Clock	             #
# Author : Arjan Lemmens                 #
# date   : 3-28-2019                     #
##########################################

restart -f


force Nrst 0
force clk_50MHz 1 
run 50
force clk_50MHz 0 
run 50 

force Nrst 1
force clk_50MHz 1 
run 50
force clk_50MHz 0 
run 50 

force clk_50MHz 1 
run 50
force clk_50MHz 0 
run 50 

force clk_50MHz 1 
run 50
force clk_50MHz 0 
run 50 

force clk_50MHz 1 
run 50
force clk_50MHz 0 
run 50 

force clk_50MHz 1 
run 50
force clk_50MHz 0 
run 50 

force clk_50MHz 1 
run 50
force clk_50MHz 0 
run 50 

force clk_50MHz 1 
run 50
force clk_50MHz 0 
run 50 

force clk_50MHz 1 
run 50
force clk_50MHz 0 
run 50 

force clk_50MHz 1 
run 50
force clk_50MHz 0 
run 50 

force clk_50MHz 1 
run 50
force clk_50MHz 0 
run 50 