##########################################
# Digital Design 21, assignment 1        #
# Author : Arjan Lemmens                 #
# Date   : 2-2-2019                      #
##########################################

restart -f

force S 0
force R 0
run 20

force S 1
force R 0
run 20

force S 0
force R 0
run 20

force S 0
force R 1
run 20

force S 0
force R 0
run 20

force S 1
force R 1
run 20
